local dap = require('dap')
local dap_ui_widgets = require('dap.ui.widgets')

vim.keymap.set('n', '<F5>', function() dap.continue() end)
vim.keymap.set('n', '<F10>', function() dap.step_over() end)
vim.keymap.set('n', '<F11>', function() dap.step_into() end)
vim.keymap.set('n', '<F12>', function() dap.step_out() end)
vim.keymap.set('n', '<Leader>b', function() dap.toggle_breakpoint() end)
vim.keymap.set('n', '<Leader>dr', function() dap.repl.open() end)
vim.keymap.set('n', '<Leader>dl', function() dap.run_last() end)
vim.keymap.set({'n', 'v'}, '<Leader>dh', function()
    dap_ui_widgets.hover()
end)
vim.keymap.set({'n', 'v'}, '<Leader>dp', function()
    dap_ui_widgets.preview()
end)
vim.keymap.set('n', '<Leader>df', function()
    dap_ui_widgets.centered_float(dap_ui_widgets.frames)
end)
vim.keymap.set('n', '<Leader>ds', function()
    dap_ui_widgets.centered_float(dap_ui_widgets.scopes)
end)

