#!/bin/bash

PID=""
APP=app-binary
APP_DIR=/opt/app-binary/bin
APP_PATH=${APP_DIR}/${APP}

function get_pid {
   PID=`pidof ${APP}`
}

function stop {
   get_pid
   if [ -z $PID ]; then
      echo "${APP} is not running."
      exit 1
   else
      echo -n "Stopping ${APP}..."
      kill -9 $PID
      sleep 1
      echo ".. Done."
   fi
}


function start {
   get_pid
   if [ -z $PID ]; then
      echo  "Starting ${APP}..."
      ${APP_PATH} # add parameters here to start
      get_pid
      echo "Done. PID=$PID"
   else
      echo "${APP} is already running, PID=$PID"
   fi
}

function restart {
   echo  "Restarting ${APP}..."
   get_pid
   if [ -z $PID ]; then
      start
   else
      stop
      sleep 5
      start
   fi
}


function status {
   get_pid
   if [ -z  $PID ]; then
      echo "${APP} is not running."
      exit 1
   else
      echo "${APP} is running, PID=$PID"
   fi
}

case "$1" in
   start)
      start
   ;;
   stop)
      stop
   ;;
   restart)
      restart
   ;;
   status)
      status
   ;;
   *)
      echo "Usage: $0 {start|stop|restart|status}"
esac
